package fetmcp.schemagen

import fetmcp.model.Family
import fetmcp.model.Mode
import fetmcp.schema.FieldKind
import fetmcp.schema.RefKind
import fetmcp.schema.ValueType
import java.io.File
import kotlin.test.Test
import kotlin.test.assertEquals
import kotlin.test.assertNotNull
import kotlin.test.assertNull
import kotlin.test.assertTrue

class SchemaGenTest {
    private val fetSrc = File(System.getProperty("fet.examples")).parentFile
    private val generated by lazy { SchemaGen.generate(fetSrc) }

    @Test
    fun `finds every constraint class`() {
        assertEquals(263, generated.types.values.count { it.family == Family.TIME })
        assertEquals(81, generated.types.values.count { it.family == Family.SPACE })
    }

    @Test
    fun `nested object list with optional inner fields`() {
        val t = generated.types.getValue("ConstraintTeacherNotAvailableTimes")
        assertEquals(Family.TIME, t.family)
        assertEquals(listOf("Teacher", "Not_Available_Time"), t.fields.map { it.name })
        val teacher = t.fields[0]
        assertEquals(FieldKind.SCALAR, teacher.kind)
        assertEquals(ValueType.STRING, teacher.value)
        assertEquals(RefKind.TEACHER, teacher.ref)
        val slots = t.fields[1]
        assertEquals(FieldKind.ARRAY, slots.kind)
        assertEquals("Number_of_Not_Available_Times", slots.countTag)
        val item = assertNotNull(slots.item)
        assertEquals(FieldKind.OBJECT, item.kind)
        assertEquals(listOf("Day", "Hour"), item.fields.map { it.name })
        assertTrue(item.fields.all { it.optional })
        assertEquals(RefKind.DAY, item.fields[0].ref)
        assertEquals(RefKind.HOUR, item.fields[1].ref)
    }

    @Test
    fun `scalar list of activity ids`() {
        val t = generated.types.getValue("ConstraintActivitiesSameStartingTime")
        val ids = t.fields.single()
        assertEquals("Activity_Id", ids.name)
        assertEquals(FieldKind.ARRAY, ids.kind)
        assertEquals("Number_of_Activities", ids.countTag)
        assertEquals(ValueType.NUMBER, ids.item?.value)
        assertEquals(RefKind.ACTIVITY, ids.item?.ref)
    }

    @Test
    fun `booleans numbers and optional lists`() {
        val pin = generated.types.getValue("ConstraintActivityPreferredStartingTime")
        assertEquals(ValueType.BOOL, pin.fields.first { it.name == "Permanently_Locked" }.value)
        assertEquals(ValueType.NUMBER, pin.fields.first { it.name == "Activity_Id" }.value)
        val room = generated.types.getValue("ConstraintActivityPreferredRoom")
        assertEquals(Family.SPACE, room.family)
        val real = room.fields.first { it.name == "Real_Room" }
        assertEquals(FieldKind.ARRAY, real.kind)
        assertTrue(real.optional)
        assertEquals("Number_of_Real_Rooms", real.countTag)
        assertEquals(RefKind.ROOM, real.item?.ref)
    }

    @Test
    fun `optional scalars and an always present but possibly empty duration`() {
        val t = generated.types.getValue("ConstraintActivitiesPreferredTimeSlots")
        assertEquals(listOf("Teacher", "Students", "Subject", "Activity_Tag", "Duration", "Preferred_Time_Slot"), t.fields.map { it.name })
        assertTrue(t.fields.first { it.name == "Duration" }.optional)
        assertEquals(RefKind.STUDENTS, t.fields.first { it.name == "Students" }.ref)
    }

    @Test
    fun `nested arrays with inner count tags`() {
        val t = generated.types.getValue("ConstraintTeacherOccupiesMaxSetsOfTimeSlotsFromSelection")
        val sets = t.fields.first { it.name == "Selected_Set_of_Time_Slots" }
        assertEquals("Number_of_Selected_Sets_of_Time_Slots", sets.countTag)
        val inner = sets.item!!.fields.single()
        assertEquals("Selected_Time_Slot", inner.name)
        assertEquals(FieldKind.ARRAY, inner.kind)
        assertEquals("Number_of_Selected_Time_Slots", inner.countTag)
        assertEquals(listOf("Day", "Hour"), inner.item!!.fields.map { it.name })
    }

    @Test
    fun `mode whitelists match the fet switches`() {
        fun count(family: Family, mode: Mode) = generated.types.values.count { it.family == family && mode in it.modes }
        assertEquals(144, count(Family.TIME, Mode.OFFICIAL))
        assertEquals(248, count(Family.TIME, Mode.MORNINGS_AFTERNOONS))
        assertEquals(147, count(Family.TIME, Mode.BLOCK_PLANNING))
        assertEquals(150, count(Family.TIME, Mode.TERMS))
        assertEquals(63, count(Family.SPACE, Mode.OFFICIAL))
        assertEquals(81, count(Family.SPACE, Mode.MORNINGS_AFTERNOONS))
        assertEquals(63, count(Family.SPACE, Mode.BLOCK_PLANNING))
        assertEquals(63, count(Family.SPACE, Mode.TERMS))
    }

    @Test
    fun `minimum activity counts come from fet's own removal code`() {
        // FET deletes a constraint when its activity list falls below these counts (rules.cpp, updateConstraintsAfterRemoval).
        assertEquals(2, generated.types.getValue("ConstraintActivitiesSameStartingTime").minActivities)
        assertEquals(2, generated.types.getValue("ConstraintMinDaysBetweenActivities").minActivities)
        assertEquals(2, generated.types.getValue("ConstraintActivitiesMaxHourlySpan").minActivities)
        assertEquals(2, generated.types.getValue("ConstraintActivitiesOccupyMaxDifferentRooms").minActivities)
        assertEquals(2, generated.types.getValue("ConstraintActivitiesSameRoomIfConsecutive").minActivities)
        assertEquals(1, generated.types.getValue("ConstraintActivitiesMaxInATerm").minActivities)
        assertEquals(1, generated.types.getValue("ConstraintActivitiesPairOfMutuallyExclusiveTimeSlots").minActivities)
        assertEquals(1, generated.types.getValue("ConstraintActivitiesOccupyMaxSetsOfTimeSlotsFromSelection").minActivities)
        // A type with no activity list has no minimum.
        assertNull(generated.types.getValue("ConstraintTeacherMaxDaysPerWeek").minActivities)
    }

    @Test
    fun `descriptions come from getDescription`() {
        assertEquals("Teacher max days per week", generated.types.getValue("ConstraintTeacherMaxDaysPerWeek").description)
        assertTrue(generated.types.values.all { it.description.isNotBlank() })
    }

    @Test
    fun `help texts are extracted for all four modes`() {
        assertEquals(setOf("Official", "Mornings_Afternoons", "Block_Planning", "Terms"), generated.help.keys)
        assertTrue("REAL day" in generated.help.getValue("Mornings_Afternoons"))
        assertTrue("Finland" in generated.help.getValue("Terms"))
    }
}
